### ISSUE TITLE
Doesn't recognize invalid regex until after you enter a test string

### ISSUE THREAD

**Issue by redmunds** [peterflynn/brackets-regex-editor#3] opened 2014-01-13 17:17 UTC
Great extension! I kinda knew about this, but finally had a need to try it out on this article by Ray Camden:

http://www.raymondcamden.com/index.cfm/2014/1/13/HTML5-Input-Patterns-and-Invalid-Regex#c7DF18EA6-06B1-70FB-1C6A97A159EF799D

When I first opened editor, there was no error message. As soon as I typed a test string I was warned that regex was invalid. Would be nice is that was detected immediately upon opening editor.

**Comment by peterflynn** [comment] 2014-01-26 00:22
@redmunds Oh, looks like the problem is just that it doesn't do an initial update when the editor is first opened.  If you edit the regex at all, it'll start showing the error message (even if no test string still).  Will fix.

**Comment by peterflynn** [comment] 2014-01-26 00:48
Fixed in version 1.1.2 -- just pushed to registry

**Closed as completed by peterflynn** 2014-01-26 00:48 UTC

**Comment by redmunds** [comment] 2014-01-28 21:30
Thanks!
